namespace ETAPI
{
    public enum ItemType
    {
        None,
        Ammo,
        AnomGasmask,
        Badge,
        Battery,
        BVGoggles,
        Document,
        Eyedrops,
        Flashlight,
        Gasmask,
        IVGoggles,
        Janitor1,
        Keycard0,
        Keycard1,
        Keycard2,
        Keycard3,
        Keycard4,
        Keycard5,
        Medkit,
        NVGoggles,
        P90,
        Radio,
        SCP714,
        SCP035,
        SCP1025,
        SCP1499,
        SNav
    }
}